.idea/.name, .idea/gradle.xml, .idea/vcs.xml, app/build.gradle.kts, app/src/main/res/layout/fragment_a.xml, app/src/main/res/layout/fragment_detalle_cita.xml, app/src/main/res/values/strings.xml
Fix: changes applied in HU1 login
Before:
After:
=> Fix: changes applied in HU1 login

app/src/main/java/com/univalle/dogappnew/view/fragments/FragmentA.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/FragmentHome.kt, app/src/main/res/drawable/theme.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/toolbar_home.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
Feat: Home page has created, added toolbar and connected to the login page
Home Page:
=> Feat: Home page has created, added toolbar and connected to the login page

app/src/main/java/com/univalle/dogappnew/view/fragments/Editar_cita.kt, app/src/main/res/layout/fragment_editar_cita.xml
=> feat Fragment_H5

.idea/appInsightsSettings.xml, app/src/main/java/com/univalle/dogappnew/view/fragments/FragmentNewAppointment.kt, app/src/main/res/drawable/outline_arrow_back_ios_24.xml, app/src/main/res/drawable/theme_toolbar.xml, app/src/main/res/layout/fragment_new_appointment.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/values/strings.xml
feat: the new quote snippet was added, as well as its toolbar
=> feat: the new quote snippet was added, as well as its toolbar

app/build.gradle.kts, app/src/main/java/com/univalle/dogappnew/view/fragments/Detalle_cita.kt, app/src/main/res/layout/fragment_detalle_cita.xml, app/src/main/res/layout/fragment_editar_cita.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
=> Feat: navigationH4

gradle/libs.versions.toml, settings.gradle.kts
=> Feat: Navigation_H4

app/build.gradle.kts
=> Feat: importar librerias

app/src/main/java/com/univalle/dogappnew/view/fragments/FragmentHome.kt, app/src/main/res/layout/fragment_new_appointment.xml, app/src/main/res/navigation/nav_graph.xml
feat: navigate to Hu3 and add a text input in New Appoiment fragment
=> feat: navigate to Hu3 and add a text input in New Appoiment fragment

app/build.gradle.kts
=> feat: add the library volley

app/src/main/java/com/univalle/dogappnew/view/MainActivity.kt
Feat:go back to the phone screen
=> Feat:go back to the phone screen

.gitignore, app/src/main/java/com/univalle/dogappnew/data/AppointmentDao.kt, app/src/main/res/layout/fragment_detalle_cita.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/colors.xml
=> Feat: Deletedatabase

.idea/betterCommentsSettings.xml, .idea/misc.xml, app/src/main/java/com/univalle/dogappnew/view/MainActivity.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_new_appointment.xml, app/src/main/res/layout/toolbar.xml, app/src/main/res/layout/toolbar_home.xml, app/src/main/res/values-night/themes.xml
feat: background color change to white not default
=> feat: background color change to white not default

.gitignore, .idea/.gitignore
fix: fixing better coment pluguin
=> fix: fixing better coment pluguin

app/src/main/java/com/univalle/dogappnew/view/adapter/PetsAdapter.kt, app/src/main/java/com/univalle/dogappnew/view/viewholder/PetsViewHolder.kt, app/src/main/res/layout/item_pet.xml
feat: adapter and viewHolder folders has created
=> feat: adapter and viewHolder folders has created

app/src/main/res/layout/fragment_detalle_cita.xml, app/src/main/res/layout/fragment_editar_cita.xml, app/src/main/res/values/strings.xml
=> feat: cambio_boton_cardview

app/src/main/java/com/univalle/dogappnew/data/AppointmentDB.kt, app/src/main/java/com/univalle/dogappnew/model/Appointment.kt, app/src/main/java/com/univalle/dogappnew/repository/AppointmentRepository.kt, app/src/main/java/com/univalle/dogappnew/utils/Constants2.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/FragmentHome.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/FragmentNewAppointment.kt, app/src/main/java/com/univalle/dogappnew/view/viewholder/PetsViewHolder.kt, app/src/main/java/com/univalle/dogappnew/viewmodel/AppointmentViewModel.kt, app/src/main/java/com/univalle/dogappnew/webservice/ApiService2.kt
Feat: conected API random images
=> Feat: conected API random images

app/src/main/java/com/univalle/dogappnew/data/AppointmentDao.kt, app/src/main/java/com/univalle/dogappnew/repository/AppointmentRepository.kt, app/src/main/java/com/univalle/dogappnew/view/adapter/PetsAdapter.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/Detalle_cita.kt, app/src/main/java/com/univalle/dogappnew/view/viewholder/PetsViewHolder.kt, app/src/main/java/com/univalle/dogappnew/viewmodel/AppointmentViewModel.kt, app/src/main/res/layout/fragment_editar_cita.xml
=> feat:funciona_h4_completo

app/src/main/java/com/univalle/dogappnew/data/AppointmentDao.kt, app/src/main/java/com/univalle/dogappnew/repository/AppointmentRepository.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/Editar_cita.kt, app/src/main/java/com/univalle/dogappnew/viewmodel/AppointmentViewModel.kt
=> feat: completado_h5

app/src/main/java/com/univalle/dogappnew/data/AppointmentDao.kt, app/src/main/java/com/univalle/dogappnew/repository/AppointmentRepository.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/Editar_cita.kt, app/src/main/java/com/univalle/dogappnew/viewmodel/AppointmentViewModel.kt, app/src/main/res/layout/fragment_editar_cita.xml, app/src/main/res/navigation/nav_graph.xml
=> feat: completada_h5

app/src/main/java/com/univalle/dogappnew/repository/AppointmentRepository.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/Detalle_cita.kt, app/src/main/java/com/univalle/dogappnew/view/fragments/Editar_cita.kt, app/src/main/java/com/univalle/dogappnew/viewmodel/AppointmentViewModel.kt
=> feat: h5_complet

app/src/main/res/navigation/nav_graph.xml
=> feat: navh_normal
